WITH NEW_VIEW_STATS AS (
    SELECT
        CHALLENGE_ID,
        SUM(TOTAL_VIEWS) AS TOTAL_VIEWS,
        SUM(TOTAL_UNIQUE_VIEWS) AS TOTAL_UNIQUE_VIEWS
    FROM VIEW_STATS
    GROUP BY CHALLENGE_ID
),

NEW_SUBMISSION_STATS AS (
    SELECT
        CHALLENGE_ID,
        SUM(TOTAL_SUBMISSIONS) AS TOTAL_SUBMISSIONS,
        SUM(TOTAL_ACCEPTED_SUBMISSIONS) AS TOTAL_ACCEPTED_SUBMISSIONS
    FROM SUBMISSION_STATS
    GROUP BY CHALLENGE_ID
),

COMBINE_TABLE AS (
    SELECT
        CO.CONTEST_ID,
        SUM(COALESCE(VS.TOTAL_VIEWS, 0)) AS TV,
        SUM(COALESCE(VS.TOTAL_UNIQUE_VIEWS, 0)) AS TUV,
        SUM(COALESCE(SS.TOTAL_SUBMISSIONS, 0)) AS TS,
        SUM(COALESCE(SS.TOTAL_ACCEPTED_SUBMISSIONS, 0)) AS TAS
    FROM CHALLENGES CH
    JOIN COLLEGES CO
        ON CO.COLLEGE_ID = CH.COLLEGE_ID
    LEFT JOIN NEW_VIEW_STATS VS
        ON CH.CHALLENGE_ID = VS.CHALLENGE_ID
    LEFT JOIN NEW_SUBMISSION_STATS SS
        ON CH.CHALLENGE_ID = SS.CHALLENGE_ID
    GROUP BY CO.CONTEST_ID
)

SELECT
    C.CONTEST_ID,
    C.HACKER_ID,
    C.NAME,
    CT.TS,
    CT.TAS,
    CT.TV,
    CT.TUV
FROM CONTESTS C
JOIN COMBINE_TABLE CT
    ON C.CONTEST_ID = CT.CONTEST_ID
WHERE CT.TS > 0
   OR CT.TAS > 0
   OR CT.TUV > 0
   OR CT.TV > 0
ORDER BY C.CONTEST_ID;