WITH HACKER_DAY_UNIQUE AS (
    SELECT DISTINCT
        HACKER_ID,
        SUBMISSION_DATE
    FROM SUBMISSIONS
),

HACKER_DAY_NUMBER AS (
    SELECT
        HACKER_ID,
        SUBMISSION_DATE,
        ROW_NUMBER() OVER (
            PARTITION BY HACKER_ID
            ORDER BY SUBMISSION_DATE
        ) AS DAY_NUMBER
    FROM HACKER_DAY_UNIQUE
),

COUNT_UNIQUE_HACKERS AS (
    SELECT
        SUBMISSION_DATE,
        COUNT(HACKER_ID) AS UNIQUE_HACKERS
    FROM HACKER_DAY_NUMBER
    WHERE DAY_NUMBER = DATEDIFF(SUBMISSION_DATE, '2016-03-01') + 1
    GROUP BY SUBMISSION_DATE
),

COUNT_MAX_SUBMISSIONS AS (
    SELECT
        SUBMISSION_DATE,
        HACKER_ID,
        COUNT(HACKER_ID) AS MAX_SUBMISSIONS
    FROM SUBMISSIONS
    GROUP BY SUBMISSION_DATE, HACKER_ID
),

RANK_MAX_SUBS AS (
    SELECT
        SUBMISSION_DATE,
        HACKER_ID,
        MAX_SUBMISSIONS,
        ROW_NUMBER() OVER (
            PARTITION BY SUBMISSION_DATE
            ORDER BY MAX_SUBMISSIONS DESC, HACKER_ID
        ) AS RN
    FROM COUNT_MAX_SUBMISSIONS
)

SELECT
    C.SUBMISSION_DATE,
    C.UNIQUE_HACKERS,
    R.HACKER_ID,
    H.NAME
FROM COUNT_UNIQUE_HACKERS C
JOIN RANK_MAX_SUBS R
    ON C.SUBMISSION_DATE = R.SUBMISSION_DATE
JOIN HACKERS H
    ON H.HACKER_ID = R.HACKER_ID
WHERE RN = 1
ORDER BY C.SUBMISSION_DATE;
