SELECT
    CASE
        WHEN G.GRADE > 7 THEN S.NAME
        ELSE 'NULL'
    END AS NAME,
    G.GRADE,
    S.MARKS
FROM STUDENTS S
JOIN GRADES G
    ON S.MARKS BETWEEN G.MIN_MARK AND G.MAX_MARK
ORDER BY
    G.GRADE DESC,
    CASE
        WHEN G.GRADE > 7 THEN S.NAME
    END,
    CASE
        WHEN G.GRADE <= 7 THEN S.MARKS
    END;