WITH COMBINED_TABLE AS (
    SELECT
        S.HACKER_ID,
        S.CHALLENGE_ID,
        S.SCORE,
        H.NAME,
        D.SCORE AS MAX_SCORE
    FROM SUBMISSIONS S
    JOIN HACKERS H
        ON S.HACKER_ID = H.HACKER_ID
    JOIN CHALLENGES C
        ON S.CHALLENGE_ID = C.CHALLENGE_ID
    JOIN DIFFICULTY D
        ON D.DIFFICULTY_LEVEL = C.DIFFICULTY_LEVEL
),
COMBINED_TABLE_2 AS (
    SELECT
        HACKER_ID,
        NAME,
        SUM(
            CASE
                WHEN SCORE = MAX_SCORE THEN 1
                ELSE 0
            END
        ) AS FULL_SCORE
    FROM COMBINED_TABLE
    GROUP BY HACKER_ID, NAME
)
SELECT
    HACKER_ID,
    NAME
FROM COMBINED_TABLE_2
WHERE FULL_SCORE > 1
ORDER BY
    FULL_SCORE DESC,
    HACKER_ID ASC;