WITH MAX_SCORE AS (
    SELECT
        HACKER_ID,
        CHALLENGE_ID,
        SCORE,
        ROW_NUMBER() OVER (
            PARTITION BY HACKER_ID, CHALLENGE_ID
            ORDER BY SCORE DESC
        ) AS RN
    FROM SUBMISSIONS S
),
SUM_SCORE AS (
    SELECT
        HACKER_ID,
        SUM(SCORE) AS FINAL_SCORE
    FROM MAX_SCORE
    WHERE RN = 1
    GROUP BY HACKER_ID
)
SELECT
    H.HACKER_ID,
    H.NAME,
    SS.FINAL_SCORE
FROM HACKERS H
JOIN SUM_SCORE SS
    ON H.HACKER_ID = SS.HACKER_ID
WHERE SS.FINAL_SCORE > 0
ORDER BY
    SS.FINAL_SCORE DESC,
    H.HACKER_ID;